### PR TITLE
Fixing incorrect scoping of the createRequesterFn function

### LINKED ISSUE #1399: Internal class extender is using a global reference to a closure variable
Receiving 404 when using GroupMembers.all(groupId);
The same group id works for Groups.show(groupId);
When performing a manual GET request to https://gitlab.com/api/v4/groups/groupid/members/all I'm getting a valid response.
```
const gitlab = Gitlab({token: "TOKEN"})
gitlab.GroupMembers.all(groupId); // Throws an error.

await axios.get("https://gitlab.com/api/v4/groups/10450319/members", { headers: { "private-token": ACCESS_TOKEN },}); // Works fine
```

I've noticed that it tries to request the api without the `/groups/` section.

### PR DESCRIPTION
**Pull request by jdalrymple**
fixes #1399

### CODE REVIEW

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`28.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/28.0.0) :rocket:

File: packages/gitbeaker-requester-utils/src/RequesterUtils.ts [hunk 1]
```diff
@@ -110,6 +110,7 @@ export function modifyServices<T>(services: T, customConfig: Record<string, unkn
 
   Object.entries(services).forEach(([k, s]) => {
     updated[k] = extendClass(s, customConfig);
+    if (k === 'GroupMembers') console.log(updated[k]);
```
Comment (RLRabinowitz) [inline packages/gitbeaker-requester-utils/src/RequesterUtils.ts:113]: Hey @jdalrymple, was this line added by mistake? I noticed `gitbreaker` started printing out for some reason, at it originated for here

Comment (jdalrymple) [reply packages/gitbeaker-requester-utils/src/RequesterUtils.ts:113]: Oh oops! Yaa ill remove it.
